name: npm-build-publish
on:
  push:
    branches:
      - main
jobs:
  npm-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      # required - sets up auth in the node env
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      # optional
      - run: yarn install
      # optional
      - run: yarn build
        env:
          CI: true
      # required
      - name: version & publish
        uses: geeman201/conventional-changelog-npm-publish/@v14
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_DIST_TAG: latest
          NPM_REGISTRY: registry.npmjs.org
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
